// Centralized constants to reduce magic numbers
module.exports = {
  DEFAULT_QUESTION_COUNT: 10,
  ADAPTIVE_SEED_COUNT: 1,
  HTTP_STATUS_CREATED: 201,
  HTTP_STATUS_NOT_IMPLEMENTED: 501,
  HTTP_STATUS_SERVICE_UNAVAILABLE: 503,
  SEC_PER_MIN: 60,
  MINUTE_IN_MS: 60000,
  MIN_TIME_ALLOC_SEC: 30,
  DEFAULT_TIME_ALLOC_SEC: 300,
  SAMPLE_MULTIPLIER: 2,
  SAMPLE_MIN_SIZE: 20,
  SCORE_EASIER_DOWN_THRESHOLD: 60,
  SCORE_HARDER_UP_THRESHOLD: 80,
};
