import React, {
  createContext,
  useContext,
  useState,
  useEffect,
  useCallback,
} from "react";

const SUPPORTED = ["en", "fr", "es", "de", "ur"];
const LABELS = {
  en: "English",
  fr: "Français",
  es: "Español",
  de: "Deutsch",
  ur: "اردو",
};

const DICTIONARY = {
  en: {
    // Common
    language_label: "Language",

    // Interview Creation Page
    create_new_interview: "Create New Interview",
    customize_interview_desc:
      "Customize your interview practice session based on your goals and preferences.",
    job_role_position: "Job Role/Position",
    job_role_placeholder: "e.g., Software Engineer, Product Manager",
    experience_level: "Experience Level",
    experience_entry: "Entry Level (0-2 years)",
    experience_intermediate: "Intermediate (2-5 years)",
    experience_senior: "Senior (5-10 years)",
    experience_expert: "Expert (10+ years)",
    adaptive_difficulty: "Adaptive Difficulty",
    adaptive_difficulty_desc:
      "Adjusts the difficulty of upcoming questions based on your performance. Starts at the selected difficulty and adapts each question.",
    interview_type: "Interview Type",
    technical_only: "Technical Only",
    technical_only_desc: "Focus on coding and technical skills",
    behavioral_only: "Behavioral Only",
    behavioral_only_desc: "Focus on soft skills and experiences",
    mixed_interview: "Mixed Interview",
    mixed_interview_desc: "Combination of technical and behavioral",
    system_design: "System Design",
    system_design_desc: "Architecture and system design questions",
    focus_areas: "Focus Areas",
    focus_areas_desc: "Select specific topics to emphasize",
    common_skills: "Common Skills",
    add_skill: "Add Skill",
    interview_duration: "Interview Duration",
    duration_15: "15 minutes",
    duration_30: "30 minutes",
    duration_45: "45 minutes",
    difficulty_level: "Difficulty Level",
    difficulty_easy: "Easy",
    difficulty_medium: "Medium",
    difficulty_hard: "Hard",
    difficulty_mixed: "Mixed",
    coding_challenges: "Include Coding Challenges",
    coding_challenges_desc: "Add live coding problems to your interview",
    number_of_challenges: "Number of Challenges",
    coding_difficulty: "Coding Difficulty",
    preferred_language: "Preferred Programming Language",
    video_answers: "Enable Video Answers",
    video_answers_desc: "Record video responses for behavioral questions",
    start_interview: "Start Interview",
    creating_interview: "Creating Interview...",
    cancel: "Cancel",
    relevant_skills: "Relevant Skills & Technologies",
    focus_areas_optional: "Focus Areas (Optional)",
    duration_minutes: "Duration (minutes)",
    duration_15_quick: "15 minutes (Quick practice)",
    duration_30_standard: "30 minutes (Standard)",
    duration_45_comprehensive: "45 minutes (Comprehensive)",
    duration_60_full: "60 minutes (Full interview)",

    // Interview Page
    facial_engagement: "Facial Engagement",
    live_transcript: "Live Transcript",
    video_disabled: "Video recording is disabled",
    interview_completed: "Interview completed - video recording disabled",
    question_of: "Question {current} of {total}",
    difficulty: "Difficulty",
    recording: "Recording",
    not_recording: "Not Recording",
    // Hardware Check Lobby
    hardware_check_title: "Hardware Check",
    hardware_check_subtitle:
      "Let's make sure your camera and microphone are working properly",
    camera_preview: "Camera Preview",
    requesting_permissions: "Requesting permissions...",
    no_camera_access: "No camera access",
    microphone_level: "Microphone Level",
    detecting_sound: "Detecting sound!",
    waiting_for_permission: "Waiting for permission...",
    speak_to_meter: "Speak to see the meter move",
    grant_permissions_mic: "Grant permissions to test your microphone",
    permission_required_title: "Permission Required",
    all_set_title: "All Set!",
    all_set_desc:
      "Your camera and microphone are working properly. You're ready to begin your interview.",
    begin_interview: "Begin Interview",
    waiting_for_permissions: "Waiting for Permissions...",
    // Interview Experience Page
    interview_title: "Interview",
    status_label: "Status",
    time_remaining_label: "Time Remaining",
    loading_interview: "Loading interview...",
    no_questions_found: "No questions found.",
    save_next: "Save & Next",
    end_session: "End Session",
    type_answer_placeholder: "Type your answer...",
    // Results Page
    dashboard_back: "Dashboard",
    print_button: "Print",
    ai_feedback_pending:
      "AI-powered advanced feedback is being generated. This page will update automatically...",
    interview_complete_title: "Interview Complete!",
    results_not_available: "Results not available",
    return_dashboard: "Return to Dashboard",

    // Emotion Analysis
    happy: "Happy",
    sad: "Sad",
    confident: "Confident",
    surprise: "Surprise",
    fear: "Fear",
    disgust: "Disgust",
    neutral: "Neutral",
    dominant_emotion: "Dominant Emotion",
    emotion_timeline: "Emotion Timeline",
    emotion_distribution: "Emotion Distribution",
    emotion_changes: "Emotion Changes",
    detection_confidence: "Detection Confidence",
    emotion_insights: "Emotional Insights",
    emotion_intensity: "Emotion Intensity (%)",
    of_recording: "of recording",
    top: "Top",
    time: "Time",
    no_emotion_data: "No emotion data available",
    analyzed_frames: "Analyzed {count} frames",
    emotion_insight_dominant:
      "Your dominant emotion was {emotion} ({percentage}%)",
    emotion_insight_stable: "You maintained emotional stability throughout",
    emotion_insight_variable:
      "Your emotions varied considerably during the interview",
    emotion_insight_positive: "You displayed positive emotions frequently",
    emotion_insight_high_confidence: "Emotion detection was highly accurate",

    // Interview UI
    current_question: "Current Question",
    your_response_notes: "Your Response Notes",
    notes_placeholder: "Take notes or outline your response here...",
    record_instruction: "Record your answer using the camera above, then click",
    submit_next: "Submit & Next",
    skip_question: "Skip Question",
    previous: "Previous",
    eye_contact: "Eye Contact",
    smile: "Smile",
    steadiness: "Steadiness",
    confidence: "Confidence",
    no_upload: "No upload",
  },
  fr: {
    // Common
    language_label: "Langue",

    // Interview Creation Page
    create_new_interview: "Créer un nouvel entretien",
    customize_interview_desc:
      "Personnalisez votre session de pratique d'entretien en fonction de vos objectifs et préférences.",
    job_role_position: "Poste/Fonction",
    job_role_placeholder: "ex., Ingénieur logiciel, Chef de produit",
    experience_level: "Niveau d'expérience",
    experience_entry: "Débutant (0-2 ans)",
    experience_intermediate: "Intermédiaire (2-5 ans)",
    experience_senior: "Senior (5-10 ans)",
    experience_expert: "Expert (10+ ans)",
    adaptive_difficulty: "Difficulté adaptative",
    adaptive_difficulty_desc:
      "Ajuste la difficulté des questions à venir en fonction de vos performances. Commence à la difficulté sélectionnée et s'adapte à chaque question.",
    interview_type: "Type d'entretien",
    technical_only: "Technique uniquement",
    technical_only_desc:
      "Concentrez-vous sur le codage et les compétences techniques",
    behavioral_only: "Comportemental uniquement",
    behavioral_only_desc:
      "Concentrez-vous sur les compétences générales et les expériences",
    mixed_interview: "Entretien mixte",
    mixed_interview_desc: "Combinaison de technique et de comportemental",
    system_design: "Conception de système",
    system_design_desc: "Questions d'architecture et de conception de système",
    focus_areas: "Domaines d'intérêt",
    focus_areas_desc:
      "Sélectionnez des sujets spécifiques à mettre en évidence",
    common_skills: "Compétences courantes",
    add_skill: "Ajouter une compétence",
    interview_duration: "Durée de l'entretien",
    duration_15: "15 minutes",
    duration_30: "30 minutes",
    duration_45: "45 minutes",
    difficulty_level: "Niveau de difficulté",
    difficulty_easy: "Facile",
    difficulty_medium: "Moyen",
    difficulty_hard: "Difficile",
    difficulty_mixed: "Mixte",
    coding_challenges: "Inclure des défis de codage",
    coding_challenges_desc:
      "Ajoutez des problèmes de codage en direct à votre entretien",
    number_of_challenges: "Nombre de défis",
    coding_difficulty: "Difficulté du codage",
    preferred_language: "Langage de programmation préféré",
    video_answers: "Activer les réponses vidéo",
    video_answers_desc:
      "Enregistrez des réponses vidéo pour les questions comportementales",
    start_interview: "Commencer l'entretien",
    creating_interview: "Création de l'entretien...",
    cancel: "Annuler",
    relevant_skills: "Compétences et technologies pertinentes",
    focus_areas_optional: "Domaines d'intérêt (facultatif)",
    duration_minutes: "Durée (minutes)",
    duration_15_quick: "15 minutes (Pratique rapide)",
    duration_30_standard: "30 minutes (Standard)",
    duration_45_comprehensive: "45 minutes (Complet)",
    duration_60_full: "60 minutes (Entretien complet)",

    // Interview Page
    facial_engagement: "Engagement facial",
    live_transcript: "Transcription en direct",
    video_disabled: "L'enregistrement vidéo est désactivé",
    interview_completed: "Entretien terminé - enregistrement vidéo désactivé",
    question_of: "Question {current} sur {total}",
    difficulty: "Difficulté",
    recording: "Enregistrement",
    not_recording: "Non enregistré",
    hardware_check_title: "Vérification matériel",
    hardware_check_subtitle:
      "Assurons-nous que votre caméra et votre micro fonctionnent correctement",
    camera_preview: "Aperçu caméra",
    requesting_permissions: "Demande d'autorisations...",
    no_camera_access: "Pas d'accès à la caméra",
    microphone_level: "Niveau du microphone",
    detecting_sound: "Son détecté !",
    waiting_for_permission: "En attente d'autorisation...",
    speak_to_meter: "Parlez pour voir le niveau bouger",
    grant_permissions_mic: "Accordez les autorisations pour tester votre micro",
    permission_required_title: "Autorisation requise",
    all_set_title: "Tout est prêt !",
    all_set_desc:
      "Votre caméra et votre micro fonctionnent correctement. Vous êtes prêt pour l'entretien.",
    begin_interview: "Commencer l'entretien",
    waiting_for_permissions: "En attente des autorisations...",
    interview_title: "Entretien",
    status_label: "Statut",
    time_remaining_label: "Temps restant",
    loading_interview: "Chargement de l'entretien...",
    no_questions_found: "Aucune question trouvée.",
    save_next: "Sauvegarder & Suivant",
    end_session: "Terminer la session",
    type_answer_placeholder: "Tapez votre réponse...",
    dashboard_back: "Tableau de bord",
    print_button: "Imprimer",
    ai_feedback_pending:
      "Le feedback avancé IA est en cours de génération. Cette page sera mise à jour automatiquement...",
    interview_complete_title: "Entretien terminé !",
    results_not_available: "Résultats non disponibles",
    return_dashboard: "Retour au tableau de bord",

    // Emotion Analysis
    happy: "Heureux",
    sad: "Triste",
    confident: "Confiant",
    surprise: "Surprise",
    fear: "Peur",
    disgust: "Dégoût",
    neutral: "Neutre",
    dominant_emotion: "Émotion dominante",
    emotion_timeline: "Chronologie des émotions",
    emotion_distribution: "Répartition des émotions",
    emotion_changes: "Changements d'émotion",
    detection_confidence: "Confiance de détection",
    emotion_insights: "Aperçus émotionnels",
    emotion_intensity: "Intensité de l'émotion (%)",
    of_recording: "de l'enregistrement",
    top: "Principal",
    time: "Temps",
    no_emotion_data: "Aucune donnée d'émotion disponible",
    analyzed_frames: "{count} images analysées",
    emotion_insight_dominant:
      "Votre émotion dominante était {emotion} ({percentage}%)",
    emotion_insight_stable: "Vous avez maintenu une stabilité émotionnelle",
    emotion_insight_variable: "Vos émotions ont varié considérablement",
    emotion_insight_positive:
      "Vous avez affiché des émotions positives fréquemment",
    emotion_insight_high_confidence:
      "La détection des émotions était très précise",

    // Interview UI
    current_question: "Question actuelle",
    your_response_notes: "Vos notes de réponse",
    notes_placeholder: "Prenez des notes ou décrivez votre réponse ici...",
    record_instruction:
      "Enregistrez votre réponse avec la caméra ci-dessus, puis cliquez",
    submit_next: "Soumettre et suivant",
    skip_question: "Passer la question",
    previous: "Précédent",
    eye_contact: "Contact visuel",
    smile: "Sourire",
    steadiness: "Stabilité",
    confidence: "Confiance",
    no_upload: "Pas de téléchargement",
  },
  es: {
    // Common
    language_label: "Idioma",

    // Interview Creation Page
    create_new_interview: "Crear nueva entrevista",
    customize_interview_desc:
      "Personaliza tu sesión de práctica de entrevista según tus objetivos y preferencias.",
    job_role_position: "Puesto/Posición",
    job_role_placeholder: "ej., Ingeniero de software, Gerente de producto",
    experience_level: "Nivel de experiencia",
    experience_entry: "Nivel inicial (0-2 años)",
    experience_intermediate: "Intermedio (2-5 años)",
    experience_senior: "Senior (5-10 años)",
    experience_expert: "Experto (10+ años)",
    adaptive_difficulty: "Dificultad adaptativa",
    adaptive_difficulty_desc:
      "Ajusta la dificultad de las próximas preguntas según tu rendimiento. Comienza con la dificultad seleccionada y se adapta con cada pregunta.",
    interview_type: "Tipo de entrevista",
    technical_only: "Solo técnica",
    technical_only_desc: "Enfócate en codificación y habilidades técnicas",
    behavioral_only: "Solo conductual",
    behavioral_only_desc: "Enfócate en habilidades blandas y experiencias",
    mixed_interview: "Entrevista mixta",
    mixed_interview_desc: "Combinación de técnica y conductual",
    system_design: "Diseño de sistemas",
    system_design_desc: "Preguntas de arquitectura y diseño de sistemas",
    focus_areas: "Áreas de enfoque",
    focus_areas_desc: "Selecciona temas específicos para enfatizar",
    common_skills: "Habilidades comunes",
    add_skill: "Agregar habilidad",
    interview_duration: "Duración de la entrevista",
    duration_15: "15 minutos",
    duration_30: "30 minutos",
    duration_45: "45 minutos",
    difficulty_level: "Nivel de dificultad",
    difficulty_easy: "Fácil",
    difficulty_medium: "Medio",
    difficulty_hard: "Difícil",
    difficulty_mixed: "Mixto",
    coding_challenges: "Incluir desafíos de codificación",
    coding_challenges_desc:
      "Agrega problemas de codificación en vivo a tu entrevista",
    number_of_challenges: "Número de desafíos",
    coding_difficulty: "Dificultad de codificación",
    preferred_language: "Lenguaje de programación preferido",
    video_answers: "Habilitar respuestas en video",
    video_answers_desc: "Graba respuestas en video para preguntas conductuales",
    start_interview: "Iniciar entrevista",
    creating_interview: "Creando entrevista...",
    cancel: "Cancelar",
    relevant_skills: "Habilidades y tecnologías relevantes",
    focus_areas_optional: "Áreas de enfoque (opcional)",
    duration_minutes: "Duración (minutos)",
    duration_15_quick: "15 minutos (Práctica rápida)",
    duration_30_standard: "30 minutos (Estándar)",
    duration_45_comprehensive: "45 minutos (Completo)",
    duration_60_full: "60 minutos (Entrevista completa)",

    // Interview Page
    facial_engagement: "Interacción facial",
    live_transcript: "Transcripción en vivo",
    video_disabled: "La grabación de vídeo está desactivada",
    interview_completed: "Entrevista completada - grabación desactivada",
    question_of: "Pregunta {current} de {total}",
    difficulty: "Dificultad",
    recording: "Grabando",
    not_recording: "No grabando",
    hardware_check_title: "Verificación de hardware",
    hardware_check_subtitle:
      "Asegurémonos de que tu cámara y micrófono funcionen correctamente",
    camera_preview: "Vista previa de cámara",
    requesting_permissions: "Solicitando permisos...",
    no_camera_access: "Sin acceso a la cámara",
    microphone_level: "Nivel de micrófono",
    detecting_sound: "¡Detectando sonido!",
    waiting_for_permission: "Esperando permiso...",
    speak_to_meter: "Habla para ver el medidor moverse",
    grant_permissions_mic: "Otorga permisos para probar tu micrófono",
    permission_required_title: "Permiso requerido",
    all_set_title: "¡Todo listo!",
    all_set_desc:
      "Tu cámara y micrófono funcionan correctamente. Estás listo para comenzar la entrevista.",
    begin_interview: "Comenzar entrevista",
    waiting_for_permissions: "Esperando permisos...",
    interview_title: "Entrevista",
    status_label: "Estado",
    time_remaining_label: "Tiempo restante",
    loading_interview: "Cargando entrevista...",
    no_questions_found: "No se encontraron preguntas.",
    save_next: "Guardar y siguiente",
    end_session: "Terminar sesión",
    type_answer_placeholder: "Escribe tu respuesta...",
    dashboard_back: "Panel",
    print_button: "Imprimir",
    ai_feedback_pending:
      "Se está generando la retroalimentación avanzada con IA. Esta página se actualizará automáticamente...",
    interview_complete_title: "¡Entrevista completada!",
    results_not_available: "Resultados no disponibles",
    return_dashboard: "Volver al panel",

    // Emotion Analysis
    happy: "Feliz",
    sad: "Triste",
    confident: "Confiado",
    surprise: "Sorpresa",
    fear: "Miedo",
    disgust: "Disgusto",
    neutral: "Neutral",
    dominant_emotion: "Emoción dominante",
    emotion_timeline: "Línea de tiempo emocional",
    emotion_distribution: "Distribución de emociones",
    emotion_changes: "Cambios emocionales",
    detection_confidence: "Confianza de detección",
    emotion_insights: "Perspectivas emocionales",
    emotion_intensity: "Intensidad emocional (%)",
    of_recording: "de la grabación",
    top: "Principal",
    time: "Tiempo",
    no_emotion_data: "No hay datos de emociones disponibles",
    analyzed_frames: "{count} fotogramas analizados",
    emotion_insight_dominant:
      "Tu emoción dominante fue {emotion} ({percentage}%)",
    emotion_insight_stable: "Mantuviste estabilidad emocional",
    emotion_insight_variable: "Tus emociones variaron considerablemente",
    emotion_insight_positive: "Mostraste emociones positivas frecuentemente",
    emotion_insight_high_confidence:
      "La detección de emociones fue muy precisa",
  },
  de: {
    // Common
    language_label: "Sprache",

    // Interview Creation Page
    create_new_interview: "Neues Interview erstellen",
    customize_interview_desc:
      "Passen Sie Ihre Interview-Übungssitzung basierend auf Ihren Zielen und Vorlieben an.",
    job_role_position: "Berufsrolle/Position",
    job_role_placeholder: "z.B. Software-Ingenieur, Produktmanager",
    experience_level: "Erfahrungsstufe",
    experience_entry: "Einstiegslevel (0-2 Jahre)",
    experience_intermediate: "Mittelstufe (2-5 Jahre)",
    experience_senior: "Senior (5-10 Jahre)",
    experience_expert: "Experte (10+ Jahre)",
    adaptive_difficulty: "Adaptive Schwierigkeit",
    adaptive_difficulty_desc:
      "Passt die Schwierigkeit kommender Fragen basierend auf Ihrer Leistung an. Beginnt mit der ausgewählten Schwierigkeit und passt sich jeder Frage an.",
    interview_type: "Interview-Typ",
    technical_only: "Nur technisch",
    technical_only_desc: "Fokus auf Programmierung und technische Fähigkeiten",
    behavioral_only: "Nur Verhaltens",
    behavioral_only_desc: "Fokus auf Soft Skills und Erfahrungen",
    mixed_interview: "Gemischtes Interview",
    mixed_interview_desc: "Kombination aus technisch und Verhaltens",
    system_design: "Systemdesign",
    system_design_desc: "Architektur- und Systemdesign-Fragen",
    focus_areas: "Schwerpunktbereiche",
    focus_areas_desc: "Wählen Sie spezifische Themen zum Betonen aus",
    common_skills: "Gängige Fähigkeiten",
    add_skill: "Fähigkeit hinzufügen",
    interview_duration: "Interview-Dauer",
    duration_15: "15 Minuten",
    duration_30: "30 Minuten",
    duration_45: "45 Minuten",
    difficulty_level: "Schwierigkeitsstufe",
    difficulty_easy: "Einfach",
    difficulty_medium: "Mittel",
    difficulty_hard: "Schwer",
    difficulty_mixed: "Gemischt",
    coding_challenges: "Programmieraufgaben einschließen",
    coding_challenges_desc:
      "Fügen Sie Live-Programmierprobleme zu Ihrem Interview hinzu",
    number_of_challenges: "Anzahl der Herausforderungen",
    coding_difficulty: "Programmierschwierigkeit",
    preferred_language: "Bevorzugte Programmiersprache",
    video_answers: "Video-Antworten aktivieren",
    video_answers_desc: "Nehmen Sie Video-Antworten für Verhaltensfragen auf",
    start_interview: "Interview starten",
    creating_interview: "Interview wird erstellt...",
    cancel: "Abbrechen",
    relevant_skills: "Relevante Fähigkeiten und Technologien",
    focus_areas_optional: "Schwerpunktbereiche (optional)",
    duration_minutes: "Dauer (Minuten)",
    duration_15_quick: "15 Minuten (Schnelle Übung)",
    duration_30_standard: "30 Minuten (Standard)",
    duration_45_comprehensive: "45 Minuten (Umfassend)",
    duration_60_full: "60 Minuten (Vollständiges Interview)",

    // Interview Page
    facial_engagement: "Gesichtsanalyse",
    live_transcript: "Live-Transkript",
    video_disabled: "Videoaufnahme ist deaktiviert",
    interview_completed: "Interview abgeschlossen - Videoaufnahme deaktiviert",
    question_of: "Frage {current} von {total}",
    difficulty: "Schwierigkeit",
    recording: "Aufnahme",
    not_recording: "Keine Aufnahme",
    hardware_check_title: "Hardwareprüfung",
    hardware_check_subtitle:
      "Stellen wir sicher, dass Kamera und Mikrofon richtig funktionieren",
    camera_preview: "Kamera-Vorschau",
    requesting_permissions: "Fordere Berechtigungen an...",
    no_camera_access: "Kein Kamerazugriff",
    microphone_level: "Mikrofonpegel",
    detecting_sound: "Ton erkannt!",
    waiting_for_permission: "Warte auf Berechtigung...",
    speak_to_meter: "Sprechen Sie, um die Anzeige zu sehen",
    grant_permissions_mic:
      "Erlauben Sie den Zugriff, um das Mikrofon zu testen",
    permission_required_title: "Berechtigung erforderlich",
    all_set_title: "Alles bereit!",
    all_set_desc:
      "Ihre Kamera und Ihr Mikrofon funktionieren. Bereit für das Interview.",
    begin_interview: "Interview beginnen",
    waiting_for_permissions: "Warte auf Berechtigungen...",
    interview_title: "Interview",
    status_label: "Status",
    time_remaining_label: "Verbleibende Zeit",
    loading_interview: "Interview wird geladen...",
    no_questions_found: "Keine Fragen gefunden.",
    save_next: "Speichern & Weiter",
    end_session: "Sitzung beenden",
    type_answer_placeholder: "Antwort eingeben...",
    dashboard_back: "Dashboard",
    print_button: "Drucken",
    ai_feedback_pending:
      "KI-Feedback wird generiert. Seite aktualisiert sich automatisch...",
    interview_complete_title: "Interview abgeschlossen!",
    results_not_available: "Ergebnisse nicht verfügbar",
    return_dashboard: "Zurück zum Dashboard",

    // Emotion Analysis
    happy: "Glücklich",
    sad: "Traurig",
    confident: "Zuversichtlich",
    surprise: "Überraschung",
    fear: "Angst",
    disgust: "Ekel",
    neutral: "Neutral",
    dominant_emotion: "Dominante Emotion",
    emotion_timeline: "Emotions-Zeitachse",
    emotion_distribution: "Emotionsverteilung",
    emotion_changes: "Emotionsveränderungen",
    detection_confidence: "Erkennungsgenauigkeit",
    emotion_insights: "Emotionale Einblicke",
    emotion_intensity: "Emotionsintensität (%)",
    of_recording: "der Aufnahme",
    top: "Top",
    time: "Zeit",
    no_emotion_data: "Keine Emotionsdaten verfügbar",
    analyzed_frames: "{count} Frames analysiert",
    emotion_insight_dominant:
      "Ihre dominante Emotion war {emotion} ({percentage}%)",
    emotion_insight_stable: "Sie haben emotionale Stabilität beibehalten",
    emotion_insight_variable: "Ihre Emotionen variierten erheblich",
    emotion_insight_positive: "Sie zeigten häufig positive Emotionen",
    emotion_insight_high_confidence: "Die Emotionserkennung war sehr genau",
  },
  ur: {
    // Common
    language_label: "زبان",

    // Interview Creation Page
    create_new_interview: "نیا انٹرویو بنائیں",
    customize_interview_desc:
      "اپنے مقاصد اور ترجیحات کی بنیاد پر اپنے انٹرویو پریکٹس سیشن کو اپنی مرضی کے مطابق بنائیں۔",
    job_role_position: "ملازمت کا کردار/عہدہ",
    job_role_placeholder: "مثال کے طور پر، سافٹ ویئر انجینئر، پروڈکٹ مینیجر",
    experience_level: "تجربے کی سطح",
    experience_entry: "ابتدائی سطح (0-2 سال)",
    experience_intermediate: "درمیانی (2-5 سال)",
    experience_senior: "سینئر (5-10 سال)",
    experience_expert: "ماہر (10+ سال)",
    adaptive_difficulty: "موافق مشکل",
    adaptive_difficulty_desc:
      "آپ کی کارکردگی کی بنیاد پر آنے والے سوالات کی مشکل کو ایڈجسٹ کرتا ہے۔ منتخب مشکل پر شروع ہوتا ہے اور ہر سوال کے ساتھ ایڈجسٹ ہوتا ہے۔",
    interview_type: "انٹرویو کی قسم",
    technical_only: "صرف تکنیکی",
    technical_only_desc: "کوڈنگ اور تکنیکی مہارتوں پر توجہ دیں",
    behavioral_only: "صرف برتاؤ",
    behavioral_only_desc: "نرم مہارتوں اور تجربات پر توجہ دیں",
    mixed_interview: "مخلوط انٹرویو",
    mixed_interview_desc: "تکنیکی اور برتاؤ کا مجموعہ",
    system_design: "سسٹم ڈیزائن",
    system_design_desc: "فن تعمیر اور سسٹم ڈیزائن کے سوالات",
    focus_areas: "توجہ کے شعبے",
    focus_areas_desc: "زور دینے کے لیے مخصوص موضوعات منتخب کریں",
    common_skills: "عام مہارتیں",
    add_skill: "مہارت شامل کریں",
    interview_duration: "انٹرویو کی مدت",
    duration_15: "15 منٹ",
    duration_30: "30 منٹ",
    duration_45: "45 منٹ",
    difficulty_level: "مشکل کی سطح",
    difficulty_easy: "آسان",
    difficulty_medium: "درمیانہ",
    difficulty_hard: "مشکل",
    difficulty_mixed: "مخلوط",
    coding_challenges: "کوڈنگ چیلنجز شامل کریں",
    coding_challenges_desc: "اپنے انٹرویو میں لائیو کوڈنگ مسائل شامل کریں",
    number_of_challenges: "چیلنجز کی تعداد",
    coding_difficulty: "کوڈنگ کی مشکل",
    preferred_language: "ترجیحی پروگرامنگ زبان",
    video_answers: "ویڈیو جوابات فعال کریں",
    video_answers_desc: "برتاؤ کے سوالات کے لیے ویڈیو جوابات ریکارڈ کریں",
    start_interview: "انٹرویو شروع کریں",
    creating_interview: "انٹرویو بنایا جا رہا ہے...",
    cancel: "منسوخ کریں",
    relevant_skills: "متعلقہ مہارتیں اور ٹیکنالوجیز",
    focus_areas_optional: "توجہ کے شعبے (اختیاری)",
    duration_minutes: "مدت (منٹ)",
    duration_15_quick: "15 منٹ (فوری مشق)",
    duration_30_standard: "30 منٹ (معیاری)",
    duration_45_comprehensive: "45 منٹ (جامع)",
    duration_60_full: "60 منٹ (مکمل انٹرویو)",

    // Interview Page
    facial_engagement: "چہرے کی مصروفیت",
    live_transcript: "براہِ راست نقل",
    video_disabled: "ویڈیو ریکارڈنگ غیر فعال ہے",
    interview_completed: "انٹرویو مکمل - ویڈیو ریکارڈنگ غیر فعال",
    question_of: "سوال {current} از {total}",
    difficulty: "مشکل",
    recording: "ریکارڈنگ",
    not_recording: "ریکارڈنگ نہیں",
    hardware_check_title: "ہارڈویئر چیک",
    hardware_check_subtitle:
      "آئیے یقینی بنائیں کہ آپ کا کیمرہ اور مائیک صحیح کام کر رہے ہیں",
    camera_preview: "کیمرہ پری ویو",
    requesting_permissions: "اجازت کی درخواست کی جا رہی ہے...",
    no_camera_access: "کیمرہ تک رسائی نہیں",
    microphone_level: "مائیکروفون لیول",
    detecting_sound: "آواز شناخت ہو رہی ہے!",
    waiting_for_permission: "اجازت کا انتظار...",
    speak_to_meter: "لیول کو حرکت میں دیکھنے کے لیے بولیں",
    grant_permissions_mic: "اپنے مائیک کو جانچنے کے لیے اجازت دیں",
    permission_required_title: "اجازت درکار ہے",
    all_set_title: "سب تیار!",
    all_set_desc:
      "آپ کا کیمرہ اور مائیک درست کام کر رہے ہیں۔ آپ انٹرویو شروع کرنے کے لیے تیار ہیں۔",
    begin_interview: "انٹرویو شروع کریں",
    waiting_for_permissions: "اجازت کا انتظار...",
    interview_title: "انٹرویو",
    status_label: "حالت",
    time_remaining_label: "بقیہ وقت",
    loading_interview: "انٹرویو لوڈ ہو رہا ہے...",
    no_questions_found: "کوئی سوال نہیں ملا۔",
    save_next: "محفوظ کریں اور آگے",
    end_session: "سیشن ختم کریں",
    type_answer_placeholder: "اپنا جواب لکھیں...",
    dashboard_back: "ڈیش بورڈ",
    print_button: "پرنٹ",
    ai_feedback_pending:
      "AI کا جدید فیڈبیک تیار ہو رہا ہے۔ یہ صفحہ خود کار طور پر اپ ڈیٹ ہوگا...",
    interview_complete_title: "انٹرویو مکمل!",
    results_not_available: "نتائج دستیاب نہیں",
    return_dashboard: "ڈیش بورڈ پر واپس جائیں",

    // Emotion Analysis
    happy: "خوش",
    sad: "اداس",
    confident: "پراعتماد",
    surprise: "حیران",
    fear: "خوف",
    disgust: "نفرت",
    neutral: "غیر جانبدار",
    dominant_emotion: "غالب جذبات",
    emotion_timeline: "جذبات کی ٹائم لائن",
    emotion_distribution: "جذبات کی تقسیم",
    emotion_changes: "جذبات کی تبدیلیاں",
    detection_confidence: "پتا لگانے کا اعتماد",
    emotion_insights: "جذباتی بصیرت",
    emotion_intensity: "جذبات کی شدت (%)",
    of_recording: "ریکارڈنگ کا",
    top: "اعلیٰ",
    time: "وقت",
    no_emotion_data: "جذبات کا ڈیٹا دستیاب نہیں",
    analyzed_frames: "{count} فریمز کا تجزیہ",
    emotion_insight_dominant: "آپ کا غالب جذبہ {emotion} تھا ({percentage}%)",
    emotion_insight_stable: "آپ نے جذباتی استحکام برقرار رکھا",
    emotion_insight_variable: "آپ کے جذبات میں کافی تبدیلی رہی",
    emotion_insight_positive: "آپ نے اکثر مثبت جذبات کا اظہار کیا",
    emotion_insight_high_confidence: "جذبات کی شناخت بہت درست تھی",

    // Interview UI
    current_question: "موجودہ سوال",
    your_response_notes: "آپ کے جواب کے نوٹس",
    notes_placeholder: "یہاں نوٹس لیں یا اپنے جواب کا خاکہ بنائیں...",
    record_instruction:
      "اوپر دیے گئے کیمرے سے اپنا جواب ریکارڈ کریں، پھر کلک کریں",
    submit_next: "جمع کریں اور آگے",
    skip_question: "سوال چھوڑیں",
    previous: "پچھلا",
    eye_contact: "آنکھ کا رابطہ",
    smile: "مسکراہٹ",
    steadiness: "استحکام",
    confidence: "اعتماد",
    no_upload: "کوئی اپ لوڈ نہیں",
  },
};

const LanguageContext = createContext({
  language: "en",
  setLanguage: () => {},
  t: (k) => k,
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const stored = localStorage.getItem("mm_language");
    return SUPPORTED.includes(stored) ? stored : "en";
  });
  useEffect(() => {
    localStorage.setItem("mm_language", language);
  }, [language]);
  const t = useCallback(
    (key) => {
      const dict = DICTIONARY[language] || DICTIONARY.en;
      return dict[key] || DICTIONARY.en[key] || key;
    },
    [language]
  );
  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, t, supported: SUPPORTED, labels: LABELS }}
    >
      {children}
    </LanguageContext.Provider>
  );
};
export const useLanguage = () => useContext(LanguageContext);
